title: Andreas Wiebe
domain: www.andreaswiebe.com
baseurl: http://www.andreaswiebe.com/test
templatename: txt
email:        contact@andreaswiebe.com
github:       https://github.com/queue-bit
linkedin:     https://www.linkedin.com/in/andreasfwiebe
twitter:      https://twitter.com/AndreasWiebe
